# Generated by Django 2.1.5 on 2019-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190112_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_logo',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
