# Generated by Django 2.1.5 on 2019-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190114_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
