# Generated by Django 2.1.4 on 2019-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190114_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_logo',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
